import Image from "next/image";
import Link from "next/link";
import { FaExternalLinkAlt } from "react-icons/fa";
import MoneyGoblin from "@/app/assets/earn/money-goblin.png";
import CashIcon from "@/app/assets/earn/cash-icon.png";

const EarnBanner = () => {
  return (
    <section className="bg-[url('/img/earn/hero-bg-mask.png')] bg-cover bg-center text-white px-6 pt-6 overflow-hidden relative">
      <div
        className="absolute inset-0 bg-grid-white/[0.05] bg-[size:40px_40px]"
        aria-hidden="true"
      />
      <div className="relative z-10 flex flex-col md:flex-row items-center justify-between">
        <div className="w-full md:w-1/2 mb-6 md:mb-0">
          <div className="flex items-center gap-2">
            <Image
              src={CashIcon}
              alt="Cash Icon"
              width={52}
              height={52}
              className="hidden md:block"
            />
            <h2 className="text-4xl font-bold text-center md:text-left w-full">
              Earning Vaults
            </h2>
          </div>
          <div className="flex md:hidden items-center justify-center w-full py-4">
            <Image
              src={MoneyGoblin}
              alt="Money Goblin Image"
              width={328}
              height={252}
            />
          </div>
          <p className="text-gray-text text-15 mb-6 font-medium text-center md:text-left">
            Deposit crypto or cash to automatically earn 50% of all the revenue
            generated by the BIDMORE platform.
          </p>
          <div className="flex items-center gap-3 justify-center md:justify-start">
            <Link
              href="https://x.com/PRINT3Rxyz"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 cursor-pointer"
            >
              <p className="bg-gradient-to-b from-[#F05722] to-[#F18522] text-gradient hover:from-[#F18522] hover:to-[#F05722] font-semibold">
                Learn More
              </p>
              <FaExternalLinkAlt className="text-printer-orange text-sm font-semibold" />
            </Link>
          </div>
        </div>
        <div className="hidden md:w-1/2 md:flex justify-end">
          {/* Unoptimized to retain quality */}
          <Image
            src={MoneyGoblin}
            alt="Money Goblin Image"
            width={328}
            height={252}
          />
        </div>
      </div>
    </section>
  );
};

export default EarnBanner;
